def country_information():
    capital = {
        "Afghanistan": "kabul",
        "Algeria": "algiers",
        "Albania": "tirane",
        "Andorra": "andora la vella",
        "Angola": "luanda",
        "Antigua And Barbuda": "saint john's",
        "Argentina": "buenos aires",
        "Armenia": "yerevan",
        "Aruba": "Oranjestad",
        "Australia": "canberra",
        "Austria": "vienna",
        "Azerbaijan": "baku",
        "The Bahamas": "Nassau",
        "Bahrain": "Manama",
        "Bangladesh": "Dhaka",
        "Barbados": "Bridgetown",
        "Belarus": "Minsk",
        "Belgium": "Brussels",
        "Belize": "Belmopan",
        "Benin": "Porto-Novo",
        "Bhutan": "Thimphu",
        "Bolivia": "La Paz, Sucre",
        "Bosnia And Herzegovina": "Sarajevo",
        "Botswana": "Gaborone",
        "Brazil": "Brasilia",
        "Brunei": "Bandar Seri Begawan",
        "Bulgaria": "Sofia",
        "Burkina Faso": "Ouagadougou",
        "Burma": "Naypyidaw",
        "Burundi": "Bujumbura",
        "Cambodia": "Phnom Penh",
        "Cameroon": "Yaounde",
        "Canada": "Ottawa",
        "Cape Verde": "Praia",
        "Central African Republic": "Bangui",
        "Chad": "N'Djamena",
        "Chile": "Santiago",
        "China": "Beijing",
        "Colombia": "Bogota",
        "Comoros": "Moroni",
        "Democratic Republic Of The Congo": "Kinshasa",
        "Republic Of The Congo": "Brazzaville",
        "Costa Rica": "San Jose",
        "Cote D'ivoire": "Yamoussoukro, Abidjan",
        "Croatia": "Zagreb",
        "Cuba": "Havana",
        "Curacao": "Willemstad",
        "Cyprus": "Nicosia",
        "Czechia": "Prague",
        "Denmark": "Copenhagen",
        "Djibouti": "Djibouti",
        "Dominica": "Rosesau",
        "Dominican Republic": "Santo Domingo",
        "East Timor": "Dilli",
        "Ecuador": "Quito",
        "Egypt": "Cairo",
        "El Salvador": "San Salvador",
        "Equatorial Guinea": "Malabo	",
        "Eritrea": "Asmara",
        "Estonia": "Tallinn",
        "Eswatini": "Mbabane, Lobamba",
        "Ethiopia": "Addis Ababa",
        "Fiji": "Suva",
        "Finland": "Helsinki",
        "France": "Paris",
        "Gabon": "Libreville",
        "Gambia": "Banjul",
        "Georgia": "Tbilisi",
        "Germany": "Berlin",
        "Ghana": "Accra",
        "Greece": "Athens",
        "Grenada": "St. George's",
        "Guatemala": "Guatemala City",
        "Guinea": "Conakry",
        "Guinea Bissau": "Bissau",
        "Guyana": "Bissau",
    }
    currency = {
        "Afghanistan": "Afghani",
        "Albania": "Lek",
        "Algeria": "Algerian Dinar",
        "Andorra": "Euro",
        "Angola": "Kwanza",
        "Antigua And Barbuda": "East Caribbean Dollar",
        "Argentina": "Argentine Peso",
        "Armenia": "Dram",
        "Aruba": "Aruban florin",
        "Australia": "Australian Dollar",
        "Austria": "Euro",
        "Azerbaijan": "Manat",
        "The Bahamas": "Bahamian Dollar",
        "Bahrain": "Bahraini Dinar",
        "Bangladesh": "Taka",
        "Barbados": "Barbadian Dollar",
        "Belarus": "Belarusian Ruble",
        "Belgium": "Euro",
        "Belize": "Belize Dollar",
        "Benin": "West African CFA Franc",
        "Bhutan": "Ngultrum",
        "Bolivia": "Boliviano",
        "Bosnia And Herzegovina": "Convertible Mark",
        "Botswana": "Pula",
        "Brazil": " 	Real",
        "Brunei": "Brunei Dollar",
        "Bulgaria": "Lev",
        "Burkina Faso": "West African CFA Franc",
        "Burma": "Burmese kyat",
        "Burundi": "Burundi Franc ",
        "Cambodia": "Riel",
        "Cameroon": "Central African CFA Franc",
        "Canada": "Canadian Dollar ",
        "Cape Verde": "Cape Verdean Escudo",
        "Central African Republic": "Central African CFA Franc",
        "Chad": "Central African CFA Franc",
        "Chile": "Chilean Peso",
        "China": "Chinese Yuan",
        "Colombia": "Colombian Peso",
        "Comoros": "Comorian Franc",
        "Democratic Republic Of The Congo": "Congolese Franc",
        "Republic Of The Congo": "Central African CFA Franc",
        "Costa Rica": "Colon",
        "Cote D'ivoire": "West African CFA Franc",
        "Croatia": "Croatian",
        "Cuba": "Cuban Peso",
        "Curacao": "Netherlands Antillean guilder",
        "Cyprus": "Euro",
        "Czechia": "Czech Koruna",
        "Denmark": "Danish Krone",
        "Djibouti": "Djiboutian Franc",
        "Dominica": "East Caribbean Dollar ",
        "Dominican Republic": "Dominican Peso",
        "East Timor": "United States Dollar ",
        "Ecuador": "United States Dollar ",
        "Egypt": "Egyptian Pound",
        "El Salvador": "United States Dollar ",
        "Equatorial Guinea": "Central African CFA Franc",
        "Eritrea": "Nakfa",
        "Estonia": "Estonian Kroon; Euro ",
        "Eswatini": "south African rand,Swazi lilangeni",
        "Ethiopia": "Birr",
        "Fiji": "Fijian Dollar",
        "Finland": "Euro",
        "France": "Euro, CFP Franc ",
        "Gabon": "Central African CFA Franc",
        "Gambia": "Dalasi",
        "Georgia": "Lari",
        "Germany": "Euro",
        "Ghana": "Ghanaian Cedi",
        "Greece": "Euro",
        "Grenada": "East Caribbean Dollar ",
        "Guatemala": "Quetzal",
        "Guinea": "Guinean Franc",
        "Guinea Bissau": "West African CFA Franc ",
        "Guyana": "Guyanese Dollar"
    }
    language = {
        "Afghanistan": "Dari Persian, Pashto",
        "Algeria": "Arabic, Tamazight, French",
        "Albania": "Albanian",
        "Andorra": "Catalan",
        "Angola": "Portuguese",
        "Antigua And Barbuda": "English",
        "Argentina": "Spanish",
        "Armenia": "Armenian",
        "Aruba": "Dutch, Papiamento",
        "Australia": "English",
        "Austria": "German",
        "Azerbaijan": "German",
        "The Bahamas": "English",
        "Bahrain": "Arabic",
        "Bangladesh": "Bangla",
        "Barbados": "English",
        "Belarus": "Belarusian",
        "Belgium": "Dutch, French, German",
        "Belize": "English",
        "Benin": "French",
        "Bhutan": "Dzongkha",
        "Bolivia": "Spanish, Quechua, Aymara",
        "Bosnia And Herzegovina": "Bosnian, Croatian, Serbian",
        "Botswana": "English, Tswana",
        "Brazil": "Portuguese",
        "Brunei": "Malay",
        "Bulgaria": "Bulgarian",
        "Burkina Faso": "French",
        "Burma": "Burmese",
        "Burundi": "Kirundi, French",
        "Cambodia": "Khmer",
        "Cameroon": "French, English",
        "Canada": "English, French",
        "Cape Verde": "Portuguese",
        "Central African Republic": "Sango, French",
        "Chad": "French, Arabic",
        "Chile": "Spanish",
        "China": "Mandarin",
        "Colombia": "Spanish",
        "Comoros": "Comorian, Arabic, French",
        "Democratic Republic Of The Congo": "French",
        "Republic Of The Congo": "French",
        "Costa Rica": "Spanish",
        "Cote D'ivoire": "French",
        "Croatia": "Kuna",
        "Cuba": "Spanish",
        "Curacao": "Dutch, English, Papiamento",
        "Cyprus": "Greek,Turkish",
        "Czechia": "Czech, Slovak",
        "Denmark": "Danish",
        "Djibouti": "Arabic, French",
        "Dominica": "English, French, Antillean Creole",
        "Dominican Republic": "Spanish",
        "East Timor": "Tetum, Portuguese, Iindonesian",
        "Ecuador": "Spanish",
        "Egypt": "Arabic",
        "El Salvador": "Spanish",
        "Equatorial Guinea": "Spanish, French; Portuguese",
        "Eritrea": "Arabic; Tigrinya; English",
        "Estonia": "Estonian",
        "Eswatini": "English, French, Swati, South African English",
        "Ethiopia": "Amharic",
        "Fiji": "English, Bau Fijian, Hindi",
        "Finland": "Finnish, Swedish",
        "France": "French",
        "Gabon": "French",
        "Gambia": "English",
        "Georgia": "Georgian",
        "Germany": "German",
        "Ghana": "English",
        "Greece": "Greek",
        "Grenada": "English, Patois",
        "Guatemala": "Spanish",
        "Guinea": "French",
        "Guinea Bissau": "Portuguese",
        "Guyana": "English",
    }
    continent = {
        "Afghanistan": "Asia",
        "Algeria": "Africa",
        "Albania": "Europe",
        "Andorra": "Europe",
        "Angola": "Africa",
        "Antigua And Barbuda": "North-America",
        "Argentina": "South-America",
        "Armenia": "Asia",
        "Aruba": "North-America, South-America",
        "Australia": "Australia",
        "Austria": "Europe",
        "Azerbaijan": "Asia, Europe",
        "The Bahamas": "North-America",
        "Bahrain": "Asia",
        "Bangladesh": "Asia",
        "Barbados": "North-America",
        "Belarus": "Europe",
        "Belgium": "Europe",
        "Belize": "North-America",
        "Benin": "Africa",
        "Bhutan": "Asia",
        "Bolivia": "South-Americara",
        "Bosnia And Herzegovina": "Europe",
        "Botswana": "Africa",
        "Brazil": "South-America",
        "Brunei": "Asia",
        "Bulgaria": "Europe",
        "Burkina Faso": "Africa",
        "Burma": "Asia",
        "Burundi": "Africa",
        "Cambodia": "Asia",
        "Cameroon": "Africa",
        "Canada": "North-America",
        "Cape Verde": "Africa",
        "Central African Republic": "Africa",
        "Chad": "Africa",
        "Chile": "South-America",
        "China": "Asia",
        "Colombia": "South-America",
        "Comoros": "Africa",
        "Democratic Republic Of The Congo": "Africa",
        "Republic Of The Congo": "Africa",
        "Costa Rica": "North-America",
        "Cote D'ivoire": "Africa",
        "Croatia": "Europe",
        "Cuba": "North-America",
        "Curacao": "North-America, South-America",
        "Cyprus": "Europe",
        "Czechia": "Europe",
        "Denmark": "Europe",
        "Djibouti": "Africa",
        "Dominica": "North-America",
        "Dominican Republic": "North-America",
        "East Timor": "Asia, Ocenia",
        "Ecuador": "South-America",
        "Egypt": "Africa, Asia",
        "El Salvador": "North-America",
        "Equatorial Guinea": "Africa",
        "Eritrea": "Africa",
        "Estonia": "Europe",
        "Eswatini": "Africa",
        "Ethiopia": "Africa",
        "Fiji": "Ocenia",
        "Finland": "Europe",
        "France": "Europe",
        "Gabon": "Africa",
        "Gambia": "Africa",
        "Georgia": "Europe, Asia",
        "Germany": "Europe",
        "Ghana": "Africa",
        "Greece": "Europe",
        "Grenada": "North America",
        "Guatemala": "North America",
        "Guinea": "Africa",
        "Guinea Bissau": "Africa",
        "Guyana": "South-America",
    }

    c = {
        "United States of America":["Washington D.C.","American Dollar","English","North America"],
        "America":["Washington D.C.","American Dollar","English","North America"],
        "Haiti": ["Port-au-Prince", "Gourde", "Haitian Creole, French", "North America"],
        "Holy See": ["Holy See", "Euro", "Italian, Latin, French, German", "Europe"],
        "Honduras": ["Tegucigalpa", "Lempira", "Spanish", "North America"],
        "Hong Kong": ["Central", "Hong Kong dollar", "Chinese, English", "Asia"],
        "Hungary": ["Budapest", "Forint", "Hungarian", "Europe"],
        "Iceland": ["Reykjavik", "Icelandic Krona", "Icelandic", "Europe"],
        "India": ["New Delhi", "Indian Rupee",
                  "Hindi, English, Urdu, Bengali, Punjabi, Sanskrit, Tamil, Kannada, Maithili, Telugu, Gujarati",
                  "Asia"],
        "Indonesia": ["Jakarta", "Rupiah", "Indonesian", "Asia"],
        "Iran": ["Tehran", "Rial", "Persian", "Asia"],
        "Iraq": ["Baghdad", "Iraqi Dinar", "Arabic; Kurdish", "Asia"],
        "Ireland": ["Dublin", "Euro", "English, Irish", "Europe"],
        "Israel": ["Jerusalem", "Shekel", "Hebrew, Arabic", "Asia"],
        "Italy": ["Rome", "Euro", "Italian", "Europe"],
        "Jamaica": ["Kingston", "Jamaican Dollar", "English", "North America"],
        "Japan": ["Tokyo", "Yen", "Japanese", "Asia"],
        "Jordan": ["Amman", "Jordanian Dinar", "Arabic", "Asia"],
        "Kazakhstan": ["Astana", "Tenge", "Kazakh, Russian", "Europe, Asia"],
        "Kenya": ["Nairobi", "Kenyan Shilling", "Swahili, English", "Africa"],
        "Kiribati": ["Swahili, English", "Kiribati Dollar", "English, Gilbertese", "Ocenia"],
        "North Korea": ["Pyongyang", "North Korean Won", "Korean", "Asia"],
        "South Korea": ["Seoul", "South Korean Won", "Korean", "Asia"],
        "Kosovo": ["Pristina", "Euro", "Albanian,Serbian", ""],
        "Kuwait": ["Kuwait City", "Kuwaiti Dollar", "Arabic, English", "Asia"],
        "Kyrgyzstan": ["Bishkek", "Som", "Kyrgyz, Russian", "Asia"],
        "Laos": ["Vientiane", "New Kiplao", "Lao", "Asia"],
        "Latvia": ["Riga", "Euro", "Latvian", "Europe"],
        "Lebanon": ["Beirut", "Lebanese Pound", "Arabic", "Asia"],
        "Lesotho": ["Maseru", "South African Rand, Lesotho Loti", "South African English,Southern Sotho, English",
                    "Asia"],
        "Liberia": ("Monrovia", "Liberian dollar", "", "Africa"),
        "Libya": ["Tripoli", "Dinar", "Arabic", "Africa"],
        "Liechtenstein": ["Vaduz", "Swiss franc", "German", "Europe"],
        "Lithuania": ["Vilnius", "Euro", "Lithuanian", "Europe"],
        "Luxembourg": ["Luxembourg Ville", "Euro", "French, German,Luxembourgish", "Europe"],
        "Macau": ["Macau", "Pataka", "Portuguese, Chinese", "Asia"],
        "Macedonia": ["Skopje", "Macedonian denar", "Macedonian", "Europe"],
        "Madagascar": ["Antananarivo", "malagasy ariary,Iraimbilanja", "French, Malagasy", "Africa"],
        "Malawi": ["Lilongwe", "Mozambican metical", "English,Chewa", "Africa"],
        "Malaysia": ["Kuala Lumpur", "Ringrit", "Malay, Malaysian", "Asia"],
        "Maldives": ["Male", "Rufia", "Dhivehi", "Asia"],
        "Mali": ["Bamako", "West African CFA franc", "French,Arabic", "Africa"],
        "Malta": ["Valletta", "Euro", "Maltese,English", "Europe"],
        "Marshall Islands": ["Majuro", "United States Dollar", "Marshllese,English", "Oceania"],
        "Mauritius": ["Port Luis", "Rupee", "English", "Africa"],
        "Mexico": ["Mexico City", "New Peso", "Sapnish", "North America"],
        "Micronesia": ["Palikir", "United States Dollar", "English", "Oceania"],
        "Moldova": ["Chișinău", "Moldovan leu", "Maldovan, Romanian", "Europe"],
        "Monaco": ["Monaco", "Euro", "French", "Europe"],
        "Mongolia": ["Ulan Bator", "Tugrik", "Monogolian", "Asia"],
        "Montenegro": ["Podgorica", "Euro", "Montenegrin", "Europe"],
        "Morocco": ["Rabat", "Morocan Dirham", "Arabic", "Africa"],
        "Mozambique": ["Maputo", "Metical", "Portuguese", "Africa"],
        "Namibia": ["Windhoek", "South African rand, nambian dollar", "German,English", "Africa"],
        "Nauru": ["Yaren", "Dollar", "Nauruan, English", "Oceania"],
        "Nepal": ["Kathmandu", "Nepalese Rupee", "Nepali", "Asia"],
        "Netherlands": ["Amsterdam", "Euro", "Dutch", "Europe"],
        "New Zealand": ["Wellington", "Dollar", "Maori, English", "Oceania"],
        "Nicaragua": ["Managua", "Nicaraguan córdoba", "Spanish", "North America"],
        "Niger": ["Niamey", "West African CFA franc", "French", "Africa"],
        "Nigeria": ["Abuja", "Naira", "Ibo, Hausa etc.", "North America"],
        "Norway": ["Oslo", "Kroner", "Kroner", "Norwegian"],
        "Oman": ["Muscat", "Rial", "Arabic", "Asia"],
        "Pakistan": ["Islamabad", "Rupee", "Urdu", "Asia"],
        "Palau": ["Melekeok", "United States Dollar", "English,Palauan", "Oceania"],
        "Palestine": ["Ramallah,East Jerusalem", "Israeli new shekel,Jordanian dinar,Egyptian Pound", "Arabic", "Asia"],
        "Panama": ["Panama City", "Balboa", "Spanish", "North America"],
        "Papua New Guinea": ["Port Moresby Papa", "Papa New Guinean Kina", "English,Hiri Motu,Tok pisin", "Oceania"],
        "Paraguay": ["Asuncion", "Guarani", "Spanish,Paraguayan Guarani", "South America"],
        "Peru": ["Lima", "Nuevo Sol", "Aymara,Spanish,Quechua", "South America"],
        "Philippines": ["Manila", "Peso", "Filipino,Tagalog", "Asia"],
        "Poland": ["Warsao", "Zioty", "Polish", "Europe"],
        "Portugal": ["Lisbon", "Euro", "Portuguese", "Europe,Africa"],
        "Qatar": ["Doha", "Riyal", "Arabic", "Asia"],
        "Romania": ["Bucharest", "Lau", "Romanian", "Europe"],
        "Russia": ["Moscow", "Rouble", "Russian", "Europe,Asia"],
        "Rwanda": ["Kigali", " Rwandan Franc", "French,Kinyarwanda,English,Swahili", "Africa"],
        "Saint Kitts and Nevis": ["Basseterre", "East Caribbean dollar", "English", "North America"],
        "St. Kitts and Nevis": ["Basseterre", "East Caribbean dollar", "English", "North America"],
        "Saint Lucia": ["Castries", "East Caribbean dollar", "English", "North America"],
        "Saint Vincent and The Grenadines": ["Kingstown", "East Caribbean dolla", "English", "North America"],
        "St. Vincent and The Grenadines": ["Kingstown", "East Caribbean dolla", "English", "North America"],
        "Samoa": ["Apia", "Tala", "English, Samoan", "Australia/Oceania"],
        "San Marino": ["San Marino", "Euro", "Italian", "Europe"],
        "Sao Tome and Principe": ["Sao Tome", "Dobra", "Portuguese", "Africa"],
        "Saudi Arabia": ["Riyadh", "Riyal", "Arabic", "Asia"],
        "Senegal": ["Dakar", "CFA Franc", "French", "Africa"],
        "Serbia": ["Belgrade", "Dinar", "Albanian, Bosnian", "Europe"],
        "Seychelles": ["Victoria", "Seychellois rupee", "English, Seselwa, French", "Africa"],
        "Sierra Leone": ["Freetown", "Sierra Leonean leone", "English", "Africa"],
        "Singapore": ["Singapore", "Dollar", "Tamil, English, Malay, Standard Mandarin, Mandarin Chinese", "Asia"],
        "Sint Maarten": ["Philipsburg", "Netherlands Antillean guilder", "Dutch, English", "North America"],
        "Slovakia": ["Bratislava", "Euro", "Slovak", "Europe"],
        "Slovenia": ["Ljubljana", "Euro", "Slovenian, Italian, Hunarian", "Europe"],
        "Solomon Islands": ["Honiara", "Solomon Islands dollar", "English", "Australia, Oceania"],
        "Somalia": ["Mogadishu", "Shilling", "Somali,Arabic", "Africa"],
        "South Africa": ["Cape Town, Pretoria, Bloemfontein", "Rand", "English, Afrikaans etc.", "Africa"],
        "South Sudan": ["Juba", "South Sudanese pound", "English", "Africa"],
        "Spain": ["Madrid", "Euro", "Spanish", "Europe"],
        "Sri Lanka": ["Colombo,Sri JayawardenepuraKotte", "Sri Lankan Rupee", "Tamil, English, Sinhala", "Asia"],
        "Sudan": ["Khartoum", "Sudanese poun", "English,arabic", "Africa"],
        "Suriname": ["Paramaribo", "Surinamese dollar", "Dutch", "South America"],
        "Swaziland": ["Lobamba", "Lilangeni", "English,French,Swati", "Africa"],
        "Sweden": ["Stockholm", "Swedish krona", "Swedish,Romani,Finnish,Yiddish", "Europe"],
        "Switzerland": ["Bern", "Swiss franc", "French,Italian,German,Romansh", "Europe"],
        "Syria": ["Damascus", "Pound", "Arabic", "Asia"],
        "Syprus": ["Nicosia", "Pound", "Greek , Turkish", "Europe"],
        "Taiwan": ["Taipei", "New Taiwan Dollar", "Chinese", "Asia"],
        "Tajikistan": ["Dushanbe", "Somoni", "Tajiki", "Asia"],
        "Tanzania": ["Dodoma", "Tanzanian shilling", "Swahili", "Africa"],
        "Thailand": ["Bangkok", "Baht", "Thai", "Africa"],
        "Timor-Leste": ["Dili", "United States Dollar", "Portuguese, Tetun", "Asia and Oceania"],
        "Togo": ["Lomé", "CFA franc", "French, German", "Africa"],
        "Tonga": ["Nukuʻalofa", "Tongan paʻanga", "Tongan, English", "Oceania"],
        "Trinidad And Tobago": ["Port of Spain", "Dollar", "English", "South America"],
        "Tunisia": ["Tunis", "Dinar", "Arabic", "Africa"],
        "Turkey": ["Ankara", "Lira", "Turkish", "Europe & Asia"],
        "Turkmenistan": ["Ashgabat", "Turkmenistan manat", "Turkmen/Russian", "Asia"],
        "Tuvalu": ["Funafuti", " ‎Australian dollar, Tuvaluan dollar", "English, Tuvaluan", "Oceania"],
        "Uganda": ["Kampala", "Shilling", "Swahili, English", "Africa"],
        "Ukraine": ["Kiev", "Karbovanets", "Ukrainian", "Europe"],
        "United Arab Emirates": ["Abu Dhabi", "Dirham", "Arabic", "Asia"],
        "United Kingdom": ["London", "Pound Sterling", "English", "Europe"],
        "Uruguay": ["Montevideo", "Uruguayan peso", "Spanish", "South America"],
        "Uzbekistan": ["Tashkent", "Uzbekistani soʻm", "Uzbek, Russian", "Asia"],
        "Vanuatu": ["Port Vila", "Vanuatu vatu", "French, Bislama,English", "Oceania"],
        "Venezuela": ["Caracas", "Bolivar", "Spanish", "South America"],
        "Vietnam": ["Ho Chi Minh City", "Dong", "Vietnamese", "Asia"],
        "Yemen": ["Sena’s", "Riyal", "Arabic", "Asia"],
        "Zaire": ["Kinshasa", "Zaire", "French", "Africa"],
        "Zambia": ["Lusaka", "Kwacha", "English", "Africa"],
        "Zimbabwe": ["Harare", "Dollar", "English, Shone, Tswana, Xhosa", "Africa"]

    }
    country_info = {}
    country_info.update(c)
    for i in capital.keys():
        n = [capital[i], currency[i], language[i], continent[i]]
        country_info[i] = n

    return country_info